
TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [791, 168, 900, 311]
GRAB_ZONE_2: [0, 0, 1, 1]
FORWARD_ZONE: [694, 316, 758, 351]
MACHINE_ZONE: [738, 317, 813, 350]
BACKWARD_ZONE: [880, 307, 984, 357]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]


TRANSITION_ZONE_01: [761, 325, 796, 340]
TRANSITION_ZONE_02: [807, 353, 822, 375]
TRANSITION_ZONE_03: [834, 379, 861, 391]
TRANSITION_ZONE_04: [895, 363, 923, 374]
TRANSITION_ZONE_05: [809, 351, 926, 358]


TRANSITION_TRESH: 40
TRANSITION_VECT: [1,1,1,1,1]
TRANSITION_MAX: 200

FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 50

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
