
TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [215, 255, 306, 341]
GRAB_ZONE_2: [0, 0, 1, 1]
FORWARD_ZONE: [153, 345, 210, 380]
MACHINE_ZONE: [183, 345, 236, 380]
BACKWARD_ZONE: [260, 332, 332, 368]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]



TRANSITION_ZONE_01: [200, 364, 224, 373]
TRANSITION_ZONE_02: [220, 376, 276, 385]
TRANSITION_ZONE_03: [209, 389, 239, 401]
TRANSITION_ZONE_04: [243, 389, 274, 401]
TRANSITION_ZONE_05: [199, 405, 225, 421]

TRANSITION_TRESH: 40
TRANSITION_VECT: [1,1,1,1,1]

TRANSITION_MAX: 200



FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 50

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
