
TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [265, 215, 356, 301]
FORWARD_ZONE: [203, 305, 260, 340]
MACHINE_ZONE: [233, 305, 286, 340]
BACKWARD_ZONE: [310, 292, 382, 328]

GRAB_ZONE_2: [0, 0, 1, 1]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]
#32 bags total

TRANSITION_ZONE_01: [245, 320, 267, 329]
TRANSITION_ZONE_02: [225, 337, 245, 351]
TRANSITION_ZONE_03: [261, 337, 282, 348]
TRANSITION_ZONE_04: [296, 336, 314, 346]
TRANSITION_ZONE_05: [324, 336, 344, 346]
TRANSITION_ZONE_06: [252, 356, 266, 366]
TRANSITION_ZONE_07: [281, 358, 296, 368]
TRANSITION_ZONE_08: [307, 358, 324, 371]

MIN_TRAN: 3
TRANSITION_TRESH: [50, 20, 50, 50, 50, 50, 50, 50]

TRANSITION_MAX: 200



FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 50

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
