
TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [841, 138, 950, 281]
FORWARD_ZONE: [744, 286, 808, 321]
MACHINE_ZONE: [778, 287, 863, 320]
BACKWARD_ZONE: [920, 277, 1034, 327]


TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]
GRAB_ZONE_2: [0, 0, 1, 1]

TRANSITION_ZONE_01: [815, 301, 845, 313]
TRANSITION_ZONE_02: [776, 325, 798, 341]
TRANSITION_ZONE_03: [811, 327, 840, 342]
TRANSITION_ZONE_04: [852, 323, 885, 338]
TRANSITION_ZONE_05: [927, 331, 957, 347]
TRANSITION_ZONE_06: [814, 353, 843, 368]
TRANSITION_ZONE_07: [870, 353, 896, 370]
TRANSITION_ZONE_08: [928, 358, 956, 372]

MIN_TRAN: 4
TRANSITION_TRESH: [50, 20, 50, 50, 50, 50, 50, 50]
TRANSITION_VECT: [1,1,1,1,1,1,1,1]
TRANSITION_MAX: 200

FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 50

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
