NAME: 'NADJET'
OUTDIR: 'POST1_NADJET'

TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [525, 159, 620, 281]
FORWARD_ZONE: [433, 286, 493, 319]
MACHINE_ZONE: [473, 286, 534, 315]
BACKWARD_ZONE: [624, 290, 708, 330]


TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]
GRAB_ZONE_2: [0, 0, 1, 1]

#38
#missde two transitions can't be fixed unless compromize zone 1 and 2
TRANSITION_ZONE_01: [487, 306, 519, 319]
TRANSITION_ZONE_02: [461, 333, 479, 345]
TRANSITION_ZONE_03: [486, 330, 504, 345]
TRANSITION_ZONE_04: [526, 332, 543, 345]
TRANSITION_ZONE_05: [563, 333, 581, 346]
TRANSITION_ZONE_06: [480, 350, 495, 364]
TRANSITION_ZONE_07: [520, 352, 536, 364]
TRANSITION_ZONE_08: [556, 353, 571, 364]




MIN_TRAN: 4
TRANSITION_TRESH: [50, 20, 50, 50, 50, 50, 50, 50]
TRANSITION_VECT: [1,1,1,1,1,1,1,1]
TRANSITION_MAX: 200


FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 23

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
