
TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [1398, 461, 1603, 700]
FORWARD_ZONE: [1239, 684, 1384, 777]
MACHINE_ZONE: [1317, 684, 1476, 777]
BACKWARD_ZONE: [1525, 671, 1715, 777]

TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]
GRAB_ZONE_2: [0, 0, 1, 1]

#missed 1
TRANSITION_ZONE_01: [1386, 717, 1448, 740]
TRANSITION_ZONE_02: [1305, 778, 1357, 810]
TRANSITION_ZONE_03: [1401, 778, 1452, 810]
TRANSITION_ZONE_04: [1480, 779, 1531, 810]
TRANSITION_ZONE_05: [1557, 776, 1607, 809]
TRANSITION_ZONE_06: [1407, 822, 1460, 858]
TRANSITION_ZONE_07: [1483, 822, 1538, 855]
TRANSITION_ZONE_08: [1564, 819, 1617, 854]

MIN_TRAN: 5
TRANSITION_TRESH: [100, 100, 100, 100, 100, 100, 100, 100]
TRANSITION_VECT: [1,1,1,1,1,1,1,1]
TRANSITION_MAX: 200


FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 23

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
