

NAME: 'AHLEM'
OUTDIR: 'POST1_AHLEM'


TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [288, 190, 384, 297]
FORWARD_ZONE: [209, 276, 280, 317]
MACHINE_ZONE: [252, 278, 323, 317]
BACKWARD_ZONE: [343, 276, 437, 321]







GRAB_ZONE_2: [0, 0, 1, 1]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]
#32 bags total

TRANSITION_ZONE_01: [258, 299, 285, 313]
TRANSITION_ZONE_02: [242, 316, 265, 333]
TRANSITION_ZONE_03: [277, 317, 300, 332]
TRANSITION_ZONE_04: [308, 319, 331, 332]
TRANSITION_ZONE_05: [336, 319, 360, 335]
TRANSITION_ZONE_06: [265, 336, 286, 352]
TRANSITION_ZONE_07: [292, 338, 317, 356]
TRANSITION_ZONE_08: [320, 341, 342, 360]

MIN_TRAN: 3
TRANSITION_TRESH: [20, 20, 20, 20, 20, 20, 20, 20]

TRANSITION_MAX: 200
TRANSITION_TEMPRATURE: 50



FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
