NAME: 'XXX'
OUTDIR: 'POST3_XXX'



TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [815, 201, 927, 309]
FORWARD_ZONE: [738, 296, 810, 342]
MACHINE_ZONE: [789, 301, 863, 342]
BACKWARD_ZONE: [885, 303, 989, 348]






TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]
GRAB_ZONE_2: [0, 0, 1, 1]

TRANSITION_ZONE_01: [788, 311, 825, 330]
TRANSITION_ZONE_02: [753, 332, 782, 355]
TRANSITION_ZONE_03: [785, 336, 821, 358]
TRANSITION_ZONE_04: [825, 335, 859, 359]
TRANSITION_ZONE_05: [889, 342, 930, 367]
TRANSITION_ZONE_06: [785, 361, 824, 389]
TRANSITION_ZONE_07: [830, 363, 875, 391]
TRANSITION_ZONE_08: [887, 369, 928, 399]

MIN_TRAN: 4
TRANSITION_TRESH: [50, 20, 50, 50, 50, 50, 50, 50]

TRANSITION_MAX: 200
TRANSITION_TEMPRATURE: 50

FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
