
NAME: 'NADJET'
OUTDIR: 'POST2_NADJET'

TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [526, 163, 634, 297]
FORWARD_ZONE: [450, 283, 515, 321]
MACHINE_ZONE: [483, 282, 560, 321]
BACKWARD_ZONE: [587, 289, 690, 330]






TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]
GRAB_ZONE_2: [0, 0, 1, 1]

#38
#missde two transitions can't be fixed unless compromize zone 1 and 2
TRANSITION_ZONE_01: [487, 298, 527, 317]
TRANSITION_ZONE_02: [464, 324, 486, 342]
TRANSITION_ZONE_03: [489, 324, 512, 343]
TRANSITION_ZONE_04: [522, 326, 550, 345]
TRANSITION_ZONE_05: [557, 328, 582, 348]
TRANSITION_ZONE_06: [479, 344, 507, 365]
TRANSITION_ZONE_07: [519, 346, 544, 367]
TRANSITION_ZONE_08: [552, 349, 577, 369]




MIN_TRAN: 4
TRANSITION_TRESH: [20, 20, 20, 20, 20, 20, 20, 20]

TRANSITION_MAX: 200
TRANSITION_TEMPRATURE: 50


FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
