
TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [235, 230, 287, 290]
GRAB_ZONE_2: [0, 0, 1, 1]
FORWARD_ZONE: [167, 296, 221, 328]
MACHINE_ZONE: [209, 298, 261, 330]
BACKWARD_ZONE: [296, 310, 358, 344]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]


TRANSITION_ZONE_01: [241, 99, 317, 132]
TRANSITION_ZONE_02: [241, 99, 317, 132]
TRANSITION_ZONE_03: [241, 99, 317, 132]
TRANSITION_ZONE_04: [241, 99, 317, 132]
TRANSITION_ZONE_05: [241, 99, 317, 132]
TRANSITION_ZONE_06: [241, 99, 317, 132]
TRANSITION_ZONE_07: [241, 99, 317, 132]
TRANSITION_ZONE_08: [241, 99, 317, 132]
TRANSITION_ZONE_09: [241, 99, 317, 132]
TRANSITION_ZONE_10: [241, 99, 317, 132]

FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 23

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
