
TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [887, 245, 949, 306]
GRAB_ZONE_2: [0, 0, 1, 1]
FORWARD_ZONE: [793, 311, 857, 341]
MACHINE_ZONE: [843, 311, 885, 340]
BACKWARD_ZONE: [967, 336, 1035, 367]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]


TRANSITION_ZONE_01: [1025, 108, 1101, 140]
TRANSITION_ZONE_02: [1025, 108, 1101, 140]
TRANSITION_ZONE_03: [1025, 108, 1101, 140]
TRANSITION_ZONE_04: [1025, 108, 1101, 140]
TRANSITION_ZONE_05: [1025, 108, 1101, 140]
TRANSITION_ZONE_06: [1025, 108, 1101, 140]
TRANSITION_ZONE_07: [1025, 108, 1101, 140]
TRANSITION_ZONE_08: [1025, 108, 1101, 140]
TRANSITION_ZONE_09: [1025, 108, 1101, 140]
TRANSITION_ZONE_10: [1025, 108, 1101, 140]

FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 23

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
