GRAB_ZONE: [750, 0, 1030, 275]
GRAB_ZONE_2: [975, 215, 1100, 325]
FORWARD_ZONE: [166, 263, 560, 450]
BACKWARD_ZONE: [970, 270, 1300, 450]
MACHINE_ZONE: [525, 270, 850, 450]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]

BACKWARD_DIRECTIONS: ['right', '']
MACHINE_DIRECTION: [' left', 'up left', 'down left', ' ']
FORWARD_DIRECTION: [' left', 'up left', 'down left']

GRAB_TEMPERATURE: 3
FORWARD_TEMPERATURE: 7
BACKWARD_TEMPERATURE: 5
MACHINE_TEMPERATURE: 10
TRANSITION_TEMPERATURE: 40

BLUE: true

MODEL_PATH: 'models/best.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'
