
TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [945, 192, 1030, 281]
GRAB_ZONE_2: [0, 0, 1, 1]
FORWARD_ZONE: [825, 291, 904, 330]
MACHINE_ZONE: [887, 289, 948, 332]
BACKWARD_ZONE: [1024, 293, 1106, 345]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]



TRANSITION_ZONE_01: [899, 320, 912, 326]
TRANSITION_ZONE_02: [917, 321, 929, 326]
TRANSITION_ZONE_03: [947, 348, 961, 354]
TRANSITION_ZONE_04: [983, 351, 995, 356]
TRANSITION_ZONE_05: [1023, 356, 1031, 362]
TRANSITION_ZONE_06: [963, 370, 972, 376]
TRANSITION_ZONE_07: [997, 371, 1007, 376]
TRANSITION_ZONE_08: [1033, 374, 1041, 379]
TRANSITION_ZONE_09: [974, 387, 983, 393]
TRANSITION_ZONE_10: [1007, 388, 1017, 394]

FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 30

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
