
TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [546, 222, 628, 295]
GRAB_ZONE_2: [0, 0, 1, 1]
FORWARD_ZONE: [465, 308, 523, 341]
MACHINE_ZONE: [502, 308, 562, 343]
BACKWARD_ZONE: [645, 316, 712, 348]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]


TRANSITION_ZONE_01: [517, 324, 527, 330]
TRANSITION_ZONE_02: [531, 324, 542, 330]
TRANSITION_ZONE_03: [551, 341, 567, 355]
TRANSITION_ZONE_04: [552, 353, 565, 365]
TRANSITION_ZONE_05: [555, 367, 560, 373]
TRANSITION_ZONE_06: [587, 346, 596, 352]
TRANSITION_ZONE_07: [587, 357, 594, 364]
TRANSITION_ZONE_08: [622, 349, 629, 356]
TRANSITION_ZONE_09: [620, 359, 627, 366]
TRANSITION_ZONE_10: [580, 365, 595, 377]

FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 23

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
