
TOTAL_STATS_ZONE: [900, 0, 1280, 330]
CURRENT_STATS_ZONE: [900, 400, 1280, 720]

GRAB_ZONE: [500, 150, 620, 260]
GRAB_ZONE_2: [0, 0, 1, 1]
FORWARD_ZONE: [320, 270, 445, 320]
MACHINE_ZONE: [400, 270, 515, 320]
BACKWARD_ZONE: [555, 290, 725, 350]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]


TRANSITION_ZONE_01: [464, 303, 473, 309]
TRANSITION_ZONE_02: [478, 304, 487, 310]

TRANSITION_ZONE_03: [480, 357, 489, 363]
TRANSITION_ZONE_04: [540, 374, 548, 380]

TRANSITION_ZONE_05: [465, 412, 474, 418]
#increase grab temp and reduce hist and expand zone a bit

TRANSITION_ZONE_06: [548, 401, 555, 408]

FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 2
FORWARD_TEMPRATURE: 5
BACKWARD_TEMPRATURE: 4
MACHINE_TEMPRATURE: 7
TRANSITION_TEMPRATURE: 30

BLUE: True

#MODEL_PATH_BLUE: 'models/green_bg_removed/weights/best.mlpackage'
#MODEL_PATH_BLUE: 'models/best_burn.mlpackage'
MODEL_PATH_BLUE: 'models/blue_feb_m.mlpackage'
MODEL_PATH: 'models/last_no_filter_green.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark1.mov'

FLOW_ZONE: [0, 0, 2, 2]
