
TOTAL_STATS_ZONE: [1500, 750, 1920, 1080]
CURRENT_STATS_ZONE: [1500, 450, 1920, 700]

GRAB_ZONE: [372, 461, 800, 900]
GRAB_ZONE_2: [1055, 215, 1056, 216]
FORWARD_ZONE: [1320, 620, 1580, 970]
BACKWARD_ZONE: [0, 540, 260, 800]
MACHINE_ZONE: [820, 682, 1320, 950]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]

FORWARD_DIRECTIONS: [' right', 'up right', 'down right']
BACKWARD_DIRECTIONS: [' left', ' ']
MACHINE_DIRECTIONS: [' right', 'up right', 'down right', ' ']

GRAB_TEMPRATURE: 0
FORWARD_TEMPRATURE: 7
BACKWARD_TEMPRATURE: 2
MACHINE_TEMPRATURE: 5
TRANSITION_TEMPRATURE: 40

BLUE: True

MODEL_PATH_BLUE: 'models/train21/weights/best.mlpackage'
MODEL_PATH: 'models/weights/last.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark8.mov'

FLOW_ZONE: [875, 705, 910, 875]
