
TOTAL_STATS_ZONE: [1500, 750, 1920, 1080]
CURRENT_STATS_ZONE: [1500, 450, 1920, 700]

GRAB_ZONE: [930, 0, 1365, 275]
GRAB_ZONE_2: [1055, 215, 1365, 361]
FORWARD_ZONE: [500, 263, 750, 550]
BACKWARD_ZONE: [1280, 270, 1650, 550]
MACHINE_ZONE: [730, 270, 1010, 550]
TABLE_ZONE: [525, 370, 970, 1075]
RED_ZONE: [1870, 95, 1885, 110]

FORWARD_DIRECTIONS: [' left', 'up left', 'down left']
BACKWARD_DIRECTIONS: [' right', ' ']
MACHINE_DIRECTIONS: [' left', 'up left', 'down left', ' ']

GRAB_TEMPRATURE: 0
FORWARD_TEMPRATURE: 7
BACKWARD_TEMPRATURE: 5
MACHINE_TEMPRATURE: 10
TRANSITION_TEMPRATURE: 40

BLUE: False

MODEL_PATH_BLUE: 'models/best.mlpackage'
MODEL_PATH: 'models/weights/last.mlpackage'
CONFIDENCE_THRESHOLD: 0.3
IOU_THRESHOLD: 0.8

VIDEO_FILE: 'videos/benchmark8.mov'

FLOW_ZONE: [940, 237, 970, 317]
